In [1]:
import numpy as np

In [5]:
a = np.array([1, 2, -3, 4])

In [6]:
a.sum()

4

In [8]:
np.abs(a)

array([1, 2, 3, 4])

In [10]:
a.std() # standard daviation

2.5495097567963922

In [11]:
a.mean()

1.0

In [13]:
a.max()

4

In [14]:
a.min()

-3

In [17]:
a.dot(a) # dot product

30

In [19]:
a + [3, 4, 5, 6]

array([ 4,  6,  2, 10])

In [23]:
a + np.array([2, 3, 8, 99])

array([  3,   5,   5, 103])

In [24]:
a - 99

array([ -98,  -97, -102,  -95])

In [2]:
b = np.array(range(185))

In [3]:
b

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [7]:
b[int(len(b)*0.25)] # quantile Q1

46

In [8]:
np.quantile(b, 0.24)

44.16

## `column_stack()`

In [11]:
hours_studied         = np.array([1,   2,   3,   4,   5   ])
assignments_completed = np.array(['a', 'b', 'c', 'd', 'e' ])

np.column_stack([hours_studied, assignments_completed])

[array(['1', 'a'], dtype='<U21'),
 array(['2', 'b'], dtype='<U21'),
 array(['3', 'c'], dtype='<U21'),
 array(['4', 'd'], dtype='<U21'),
 array(['5', 'e'], dtype='<U21')]