## libs

In [33]:
import numpy as np

## Load Dataset

In [34]:
from dataset import X, Y

In [35]:
def get_sample(number):
  return {
    'input': X[number-1],
    'output': Y[number-1]
  }

In [36]:
first_sample = get_sample(1)
print(first_sample)

{'input': array([10, 15,  1]), 'output': 1}


In [37]:
# Sigmoid function
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [38]:
# Derivative of the sigmoid function
def sigmoid_derivative(x):
    return x * (1 - x)

## Neuron
- weights (initial = 0)
- bias (initial 0)

![Neuron](img/neuron.png)

In [39]:
weights = np.zeros(3)
bias = 0

In [40]:
# learning rate
learning_rate = 0.1

## Forward Pass 1

In [41]:
weighted_sum = np.dot(
  first_sample['input'],
  weights
) + bias
weighted_sum

0.0

output is zero because all weights are zero. and bias is zero

In [42]:
predicted = sigmoid(weighted_sum)
predicted

0.5

## Backward Pass 1

In [43]:
error = first_sample['output'] - predicted
error

0.5

In [44]:
gradient = error * sigmoid_derivative(predicted)
gradient

0.125

In [45]:
weights # weights before

array([0., 0., 0.])

In [46]:
weights += learning_rate * gradient * first_sample['input']
weights # weights after

array([0.125 , 0.1875, 0.0125])

## Forward Pass 2

In [47]:
second_sample = get_sample(2)
second_sample

{'input': array([ 5, 10,  0]), 'output': 0}

In [48]:
weighted_sum = np.dot(
  second_sample['input'],
  weights
) + bias
weighted_sum

2.5

In [49]:
predicted = sigmoid(weighted_sum)
predicted

0.9241418199787566

## Backward Pass 2

In [50]:
error = second_sample['output'] - predicted
error

-0.9241418199787566

In [51]:
gradient = error * sigmoid_derivative(predicted)
gradient

-0.06478577619527104

In [52]:
weights # before

array([0.125 , 0.1875, 0.0125])

In [53]:
weights += learning_rate * gradient * second_sample['input']
weights # weights after

array([0.09260711, 0.12271422, 0.0125    ])

## Forward Pass 3

In [54]:
third_sample = get_sample(3)
third_sample

{'input': array([ 8, 12,  1]), 'output': 1}

In [55]:
weighted_sum = np.dot(
  second_sample['input'],
  weights
) + bias
weighted_sum

1.690177797559112

In [56]:
predicted = sigmoid(weighted_sum)
predicted

0.8442475405538364

## Backward Pass 3

In [57]:
error = third_sample['output'] - predicted
error

0.15575245944616356

In [58]:
gradient = error * sigmoid_derivative(predicted)
gradient

0.020480456402131218

In [59]:
weights # before

array([0.09260711, 0.12271422, 0.0125    ])

In [60]:
weights += learning_rate * gradient * third_sample['input']
weights # weights after

array([0.10899148, 0.14729077, 0.01454805])

## Loop

so in this way, we change weights for every sample a bit.

and we run all samples more than once. it is called `number of epochs`.

100 epochs means we shall run all samples 100 times.

let us make a loop for that

In [61]:
epochs = 100

In [62]:
# Training
for epoch in range(epochs):
  for i in range(len(Y)):
    # Forward pass
    weighted_sum = np.dot(X[i], weights) + bias
    predicted = sigmoid(weighted_sum)
    
    # Error
    error = Y[i] - predicted
    
    # Backward pass: gradient
    d_predicted = error * sigmoid_derivative(predicted)
    
    # update weights
    weights += learning_rate * d_predicted * X[i]
    bias += learning_rate * d_predicted

## Testing

now let us test against all inputs

In [63]:
# Testing
print("Predictions:")
for i in range(len(X)):
  weighted_sum = np.dot(X[i], weights) + bias
  predicted = sigmoid(weighted_sum)
  
  binary_output = 1 if predicted >= 0.5 else 0
  
  print(f"Input #: {i}, Perception Result = {round(predicted, 2)},\tPredicted Output: {binary_output}, Actual Output: {Y[i]}")

Predictions:
Input #: 0, Perception Result = 0.89,	Predicted Output: 1, Actual Output: 1
Input #: 1, Perception Result = 0.1,	Predicted Output: 0, Actual Output: 0
Input #: 2, Perception Result = 0.85,	Predicted Output: 1, Actual Output: 1
Input #: 3, Perception Result = 0.14,	Predicted Output: 0, Actual Output: 0
Input #: 4, Perception Result = 0.56,	Predicted Output: 1, Actual Output: 1
Input #: 5, Perception Result = 0.1,	Predicted Output: 0, Actual Output: 0
Input #: 6, Perception Result = 0.89,	Predicted Output: 1, Actual Output: 1
Input #: 7, Perception Result = 0.1,	Predicted Output: 0, Actual Output: 0
Input #: 8, Perception Result = 0.25,	Predicted Output: 0, Actual Output: 0
Input #: 9, Perception Result = 0.92,	Predicted Output: 1, Actual Output: 1


In [64]:
weights

array([ 0.73538101, -0.3670174 ,  2.44989305])

In [65]:
bias

-2.206987184870766

## Summary
hance our model just trained its weights and bias in a way
that it predicts a value closer to actual output